---

- meta: flush_handlers

- name: WILDFLY | Wait for Wildfly to start
  wait_for:
    path: "{{ wildfly_install_path }}/{{ wildFly_mode }}/log"
    state: present

- name: WILDFLY LOGS | Manage symlink
  file:
    src: "{{ wildfly_install_path }}/{{ wildFly_mode }}/log"
    dest: "{{ wildfly_logs_path }}"
    owner: root
    group: root
    state: link
    force: yes
