---

- name: WILDFLY APPLICATION USERS | Configuration
  shell: "{{ wildfly_install_link }}/bin/add-user.sh -s -a {{ item.name }} {{ item.password }}"
  with_items: "{{ wildfly_application_users }}"
  become: True
  become_user: "{{ wildfly_user }}"
